import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css"
import QueryProvider from "@/providers/QueryProviders";
import ThemeProvider from "@/providers/ThemeProvider";
import ThemeToggle from "@/components/reusable/ThemeToggle";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html
    lang="en"
    suppressHydrationWarning
    className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
  >
    <body className="min-h-full flex flex-col">
      <ThemeProvider>
        <QueryProvider>
          <ThemeToggle/>
          {children}
        </QueryProvider>
      </ThemeProvider>
    </body>
  </html>
)

export default RootLayout
